# SPDX-License-Identifier: BSD-3-Clause
# bpsk_hw kernel test (ld.qam hardware accelerator path) — see
# ../../common/kernel.mk for the shared build/test/clean rules.

KERNEL = bpsk_hw
SRCS   = test_psk_hw.c kernel/psk_hw.c

include ../../common/kernel.mk
