# SPDX-License-Identifier: BSD-3-Clause
# bpsk kernel test — see ../../common/kernel.mk for the shared build/test/clean rules.

KERNEL = bpsk
SRCS   = test_psk.c kernel/psk.c ../../../vspa-sdk/src/vcpu.sx

include ../../common/kernel.mk
