// SPDX-License-Identifier: BSD-3-Clause
// bpsk kernel test harness.
//
// bit_in is N single-precision floats, each exactly 0.0f or 1.0f (matching
// mod_bpsk's S1straight + single-precision read). Reference is the same
// AMPLITUDE-scaled +-1 mapping as kernel/psk.c (currently 2*0.9*bit - 0.9),
// encoded in VSPA half-fixed (sign-magnitude), packed two real values per
// 32-bit word (low 16 bits = even element, high 16 bits = odd element),
// generated by gen_vectors.py -- not the qam pipeline's oracle.
//
// The extern declaration below matches mod_bpsk's real signature exactly
// (vspa_complex_fixed16*, not void*) so the prototype seen here agrees with
// the actual definition in kernel/psk.c. bpskOut is still plain packed words
// for vspa_array_cmp's sake, so it's cast to the real parameter type at the
// call site instead.

#include <stdint.h>
#include <stdio.h>
#include <vspa/intrinsics.h>
#include "test_utils.h"

extern void mod_bpsk(uint32_t *bit_in, vspa_complex_fixed16 *bpsk_out, uint32_t N);

#define N_BITS       32
#define N_OUT_WORDS  (N_BITS / 2)   // 2 packed real half-fixed values per word

// Compile-time-baked vectors from gen_vectors.py.
static const float INPUT_DATA[N_BITS] = {
#include "vectors/input.hex"
};

static const unsigned int REF_DATA[N_OUT_WORDS] = {
#include "vectors/ref.hex"
};

// Vector-aligned BSS buffers. bpskOut is sized to a full VRA line (32 words)
// as a safety margin in case one rmad/wr.straight pass produces more valid
// elements than N_OUT_WORDS accounts for -- only the first N_OUT_WORDS are
// compared against REF_DATA.
_VSPA_VECTOR_ALIGN static float bitIn[N_BITS];
_VSPA_VECTOR_ALIGN static unsigned int bpskOut[32];

int main(void)
{
    int i;

    for (i = 0; i < N_BITS; i++)
        bitIn[i] = INPUT_DATA[i];

    KCYC_INIT();
    KCYC_START();
    mod_bpsk((uint32_t *)bitIn, (vspa_complex_fixed16 *)bpskOut, (uint32_t)N_BITS);
    KCYC_STOP_PRINT();

    return vspa_array_cmp(bpskOut, REF_DATA, N_OUT_WORDS);
}
